#!/usr/bin/env ruby

# Make this script executeable and place it in your path.
# Add commonly ssh'd servers to the SERVERS hash.
# Then type 'con home' which will ssh you into your home. The :alias key is what you reference the connection by.
# Using aliases accomplishes the same thing. 
# This is (was) an experiment.

# List of Servers
SERVERS = [
  {:host => "xx.xxx.xx.xx",   :alias => "home",         :username => "dave",        :port => "22"},
]

# Finds the correct Server
def find_by_alias(alias_to_find)
  SERVERS.find {|server| server[:alias] == alias_to_find}
end

selected_alias = ARGV[0] 

if selected_alias.nil? or find_by_alias(selected_alias).nil?
  puts "--------   You need to supply a valid Alias   --------\n"  
  SERVERS.each {|server| puts "Alias: '#{server[:alias]} - '#{server[:host]}'"}
else
  connection = find_by_alias(selected_alias)
  exec "ssh #{connection[:username]}@#{connection[:host]} -p #{connection[:port]}"
end